# Generated by Django 3.1 on 2020-11-24 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20201110_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateField(auto_now=True)),
                ('cheese', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.cheese')),
            ],
        ),
    ]
